#!/usr/bin/env python3
"""Embed brand SVGs + alphabet glyphs into brand-assets.js.

fetch() fails on file:// and adds latency everywhere else, so all brand
assets ship inlined as one JS constant. Re-run after changing anything in
assets/brand/ or assets/alphabet/.
"""
import json
import re
import string
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / 'assets' / 'brand'
ALPHA = ROOT / 'assets' / 'alphabet'
OUT = ROOT / 'brand-assets.js'


def read(p):
    return p.read_text()


def sanitize_mascot(svg):
    """Strip the shared .st0 stylesheet and ink via currentColor."""
    svg = re.sub(r'<defs>.*?</defs>', '', svg, flags=re.S)
    svg = svg.replace('class="st0"', 'fill="currentColor"')
    return svg


assets = {
    'logo': read(BRAND / 'blexx_logo.svg'),
    'mark': read(BRAND / 'blexx_mark.svg'),
    'mascots': {
        'chance': sanitize_mascot(read(BRAND / 'chance_mascot.svg')),
        'devotion': sanitize_mascot(read(BRAND / 'devotion_mascot.svg')),
        'manifestation': sanitize_mascot(read(BRAND / 'manifestation_mascot.svg')),
    },
    'alphabet': {c: read(ALPHA / f'{c}.svg') for c in string.ascii_lowercase},
}

js = ('// GENERATED by tools/build_assets.py — do not edit by hand.\n'
      '// Brand assets inlined so the app needs no fetch() (works on file://).\n'
      'const EMBEDDED_ASSETS = ' + json.dumps(assets) + ';\n')
OUT.write_text(js)
print(f'wrote {OUT} ({OUT.stat().st_size // 1024}KB)')
